### ISSUE TITLE
Project don't run with cargo

### ISSUE THREAD

**Issue by flaviogranato** [mathall/rim#14]
This project don't run or compile with cargo (cargo 0.15.0-nightly (298a012 2016-12-20) ) and rustc (rustc 1.14.0 (e8a012324 2016-12-16) )

We receive that message below:

```
    Compiling rim v0.0.1 (file:///home/flavio/bin/rim)
error[E0554]: #[feature] may not be used on the stable release channel
 --> src/rim.rs:9:1
  |
9 | #![feature(mpsc_select)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: #[feature] may not be used on the stable release channel
  --> src/rim.rs:10:1
   |
10 | #![feature(slice_patterns)]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `rim`.

To learn more, run the command again with --verbose.
```

**Comment by mathall** [comment]
Hey, seems you're using stable rustc there. You'll need to compile with nightly to get those feature gates working.

**Comment by flaviogranato** [comment]
rustc 1.16.0-nightly (ff591b6dc 2017-01-15)

And the same error

```
   Compiling rim v0.0.1 (file:///home/flavio/bin/rim)
error[E0529]: expected an array or slice, found `&[keymap::Key]`
   --> src/command.rs:270:11
    |
270 |           []            =>
    |           ^^ pattern cannot match with input type `&[keymap::Key]`
    |
    = help: the semantics of slice patterns changed recently; see issue #23121

error[E0529]: expected an array or slice, found `&[keymap::Key]`
   --> src/command.rs:273:11
    |
273 |           [key, keys..] => {
    |           ^^^^^^^^^^^^^ pattern cannot match with input type `&[keymap::Key]`
    |
    = help: the semantics of slice patterns changed recently; see issue #23121

error[E0529]: expected an array or slice, found `&[keymap::Key]`
   --> src/command.rs:283:11
    |
283 |           []     => Keychain::Cmd(new_cmd),
    |           ^^ pattern cannot match with input type `&[keymap::Key]`
    |
    = help: the semantics of slice patterns changed recently; see issue #23121

error: aborting due to 3 previous errors

error: Could not compile `rim`.

To learn more, run the command again with --verbose.

```

**Comment by mathall** [comment]
Ah you're right, different error though. As the message says, the semantics of slice patterns changed recently and I haven't gotten around to fixing it. I'll see if I can get around to push anything by the weekend. For now you could just put a & ahead of the arms, and a ref ahead of keys like `&[key, ref keys..] => {` etc.

**Comment by mathall** [comment]
Better late than never?
